#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Detected the ."""

from kittysploit import *
from lib.protocols.http.http_client import Http_client


class Module(Scanner, Http_client):
    __info__ = {
        'name': 'Yarn Integrity File Disclosure Detection',
        'description': 'Detected the .yarn-integrity file generated by the Yarn package manager and stored in node_modules/.yarn-integrity.Exposure of this file could have revealed sensitive dependency information and aided attackers in identifying vulnerable packages for supply chain attacks.',
        'author': ['KittySploit Team'],
        'severity': 'info',
        'tags': ['web', 'scanner', 'exposure', 'yarn', 'node', 'npm', 'misconfig'],
        'agent': {
            'risk': 'active',
            'effects': ['network_probe'],
            'expected_requests': 2,
            'reversible': True,
            'approval_required': False,
            'produces': ['tech_hints', 'risk_signals', 'endpoints'],
            'cost': 1.0,
            'noise': 0.3,
            'value': 1.0,
            'requires': {
                'min_endpoints': 0,
                'min_params': 0,
                'tech_hints_any': [],
                'tech_hints_all': [],
                'specializations_any': [],
                'risk_signals_any': [],
                'auth_session': False,
                'capabilities_any': [],
                'capabilities_all': [],
                'confidence_min': {},
                'confidence_min_any': {},
                'endpoint_pattern_any': [],
                'param_any': [],
                'api_surface_ready': False,
            },
            'chain': {
                'produces_capabilities': [
                    {
                        'capability': 'admin_surface',
                        'from_detail': '',
                    },
                ],
                'consumes_capabilities': [],
                'option_bindings': {},
                'suggested_followups': ['auxiliary/scanner/http/login_page_detector'],
            },
        },
        'references': [
            'https://classic.yarnpkg.com/lang/en/docs/yarn-lock/',
            'https://github.com/yarnpkg/yarn/blob/master/src/integrity-checker.js',
        ],
    }

    def run(self):
        for path in ('/node_modules/.yarn-integrity', '/.yarn-integrity'):
            r = self.http_request(method="GET", path=path, allow_redirects=False)
            if not r or r.status_code != 200:
                continue
            body = r.text or ""
            body_any = ('topLevelPatterns', 'linkedModules', 'modulesFolders',)
            body_all = ('systemParams', 'lockfileEntries',)
            if (any(m in body for m in body_any)) and (all(m in body for m in body_all)):
                self.set_info(
                    severity='info',
                    reason="Yarn Integrity File Disclosure detected",
                    path=path,
                )
                return True
        return False

